[package]
name = "tuff_schemas"
version = "0.1.0"
edition = "2021"

[dependencies]
flatbuffers = "23.5.26"
serde = { version = "1.0", features = ["derive"] }

[build-dependencies]
flatbuffers = "23.5.26"
