[package]
name = "tuff_common"
version = "0.1.0"
edition = "2021"

[dependencies]
tuff_schemas = { path = "../../shared/schemas" }
flatbuffers = "2.0.8"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
thiserror = "1.0"
